## Set which python version to use in including.
import os
print("Detecting python version")
f = open("autogenerated_python_include.h", "w+")

if os.path.isdir("/usr/include/python3.9"):
    f.write("#include <python3.9/Python.h>")
    print("Set for python 3.9")
elif os.path.isdir("/usr/include/python3.7"):
    f.write("#include <python3.7/Python.h>")
    print("Set for python 3.7")
